steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/order-system-mvp', '.']

  # Step 2: Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/order-system-mvp']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'order-system',
        '--image', 'gcr.io/$PROJECT_ID/order-system-mvp',
        '--region', 'asia-east1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - gcr.io/$PROJECT_ID/order-system-mvp
